apiVersion: v1
kind: Service
metadata:
  name: info910-adminer-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: info910-adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: info910-adminer-deploy
spec:
  selector:
    matchLabels:
      app: info910-adminer
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: info910-adminer
    spec:
      containers:
        - image: adminer:latest
          name: info910-adminer
          env:
          - name: PMA_ARBITRARY
            value: "1"
          - name: PMA_HOST
            value: mysql
          - name: UPLOAD_LIMIT
            value: 20M
          ports:
            - containerPort: 8080
      restartPolicy: Always
