apiVersion: v1
kind: Secret
metadata:
  name: info910-bdd-secret
type: kubernetes.io/basic-auth
stringData:
  password: "R!OT"
---
apiVersion: v1
kind: Secret
metadata:
  name: info910-bdd
type: kubernetes.io/basic-auth
stringData:
  root_password: "R!OT"
  database: "JDR"
  user: "root"
  user_password: "R!OT"
